### ISSUE TITLE
原来HTTP响应头与状态码的文章被移除了？

### ISSUE THREAD

**Issue by 853486395** [wx-chevalier/Distributed-Infrastructure-Series#3]
原来的链接地址是https://github.com/wxyyxc1992/infrastructure-handbook/blob/master/Network/Protocol/HTTP/http-response.md
现在已经找不着了。

**Comment by wx-chevalier** [comment]
https://github.com/wxyyxc1992/ServerSideApplication-Development-And-System-Architecture/tree/master/ServerSide-Application-Development-Fundamentals/HTTP 移动到了这里
